[tool.poetry]
name = "modeltools"
version = "0.1.1"
description = ""
authors = ["Beatriz"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
