# Actions crea contenedores para ejecutar las acciones.
# Cuando se salta actions SIEMPRE se ejecuta lo mismo para todos (versiones...)
# Microsoft es dueño de GitHub. Cuando hacemos un push en sus data centers se ejecuta.
# https://docs.github.com/en/actions

name: Building  # Nombre del workflow
on: [push]  # Cuando se ejecuta ( ${{ github.event_name }} )
jobs: # Solo vamos a crear un job.
  building:
    runs-on: ubuntu-latest  # Job will run on: ${{ runner.os }}
    steps:
      - uses: actions/checkout@v3  # Checks out repository (TestGHBea) code. Descargar el repositorio, el código que hay detrás para hacer esto está en https://github.com/actions/checkout. Puede configuarse modificando las variables. Branch: ${{ github.ref }} y el Repository: ${{ github.repository }}
      - uses: actions/setup-python@v4    # Acción que instala python: github.com/-actions/setup-python
        with:
          python-version: "3.10"
      - name: Install Poetry Action  # https://github.com/marketplace/actions/install-poetry-action
        uses: snok/install-poetry@v1.3.1
      - run: poetry build  # run ejecuta comando de consola en el repo. Comando para empaquetar con poetry.
      - run: ls ${{ github.workspace }}  # Comando 